#!/bin/zsh

#du -a / 2>/dev/null | awk '{print $2}' | fzf | xargs -r $EDITOR
#tree -faiF / 2>/dev/null | grep -v /$ | fzf | xargs -r $EDITOR
#find / -type f 2>/dev/null | fzf | xargs -r $EDITOR
#find / -type f -print0 2>/dev/null | xargs -0 file | grep -P text | cut -d: -f1 | fzf



dir=$1
[[ "$dir" = "" ]] && dir="/"



selection=$(find $dir -maxdepth 8 -mount 2>/dev/null | grep -vEi '/proc/|/dev/|/tmp/|cache|/sys/' | fzf --preview='file {} && echo "" && bat -p --color=always {} 2>/dev/null')




filetype=$(file $selection | awk '{print $2}')

dirpath=$(echo $selection | rev | cut -d'/' -f2- | rev) # if its a textfile remove last element


[[ "$filetype" = "directory" ]] && cd $selection
[[ "$filetype" = "PNG" ]] || [[ "$filetype" = "JPEG" ]] && cd $dirpath && $IMGVIEWER $selection
[[ "$filetype" = "Unicode" ]] || [[ "$filetype" = "Python" ]] || [[ "$filetype" = "ASCII" ]] || [[ "$filetype" = "POSIX" ]] || [[ "$filetype" = "Paul" ]] && cd $dirpath && $EDITOR $selection # if its a txtfile, edit it and then cd into dir





