#!/bin/zsh

# Usage: $ fuzzy <dir>
# default dir: /

# Allows you to fuzzy find all files on the system on then opens files with corresponding programs

# ToDo:
# Icons
# Modes (pacman)
# Better filetype detection



dir=$1
[[ "$dir" = "" ]] && dir="/"


selection=$(find $dir -maxdepth 8 -mount 2>/dev/null | grep -vEi '/proc/|/dev/|/tmp/|cache|/sys/' | fzf --preview='file {} && echo "" && bat -p --color=always {} 2>/dev/null')
#selection=$(find $dir -maxdepth 8 -mount 2>/dev/null | grep -vEi '/proc/|/dev/|/tmp/|cache|/sys/' | fzy)


filetype=$(file $selection | awk '{print $2}')
dirpath=$(echo $selection | rev | cut -d'/' -f2- | rev) # if its a textfile remove last element


# directories
[[ "$filetype" = "directory" ]] && cd $selection

# images
[[ "$filetype" = "PNG" ]] || [[ "$filetype" = "JPEG" ]] && cd $dirpath && $IMGVIEWER $selection

# text files
[[ "$filetype" = "Unicode" ]] || [[ "$filetype" = "Python" ]] || [[ "$filetype" = "ASCII" ]] || [[ "$filetype" = "POSIX" ]] || [[ "$filetype" = "Paul" ]] && cd $dirpath && $EDITOR $selection

# shell scripts
shebang=$(cat $selection | sed 1q | grep \#!)
[[ "$shebang" != "" ]] && cd $dirpath && $EDITOR $selection





