#!/bin/zsh

#du -a / 2>/dev/null | awk '{print $2}' | fzf | xargs -r $EDITOR
#tree -faiF / 2>/dev/null | grep -v /$ | fzf | xargs -r $EDITOR
#find / -type f 2>/dev/null | fzf | xargs -r $EDITOR
#find / -type f -print0 2>/dev/null | xargs -0 file | grep -P text | cut -d: -f1 | fzf



dir=$1
[[ "$dir" = "" ]] && dir="/"

#selection=$(tree -fai $dir 2>/dev/null | fzf)

#selection=$(tree -fai $dir 2>/dev/null | grep -v "/proc/" | grep -v "/dev/" | grep -v ">" | grep -v "/tmp/"| grep -vi "cache" | fzf --color='fg:#cad3f5,bg:#363a4f,fg+:#8aadf4,bg+:#464d64,pointer:#ed8796,prompt:#8aadf4,spinner:#8aadf4,info:#b7bdf8,border:#cad3f5' --preview='head -$LINES {}')



# -L n is maximum depth
# grep -vEi ... E regex, v ignore matches, i case insensitive

selection=$(tree -fai -L 8 --noreport $dir 2>/dev/null | grep -vEi '/proc/|/dev/|>|/tmp/|cache|/sys/' | fzf --color='fg:#cad3f5,bg:#363a4f,fg+:#8aadf4,bg+:#464d64,pointer:#ed8796,prompt:#8aadf4,spinner:#8aadf4,info:#b7bdf8,border:#cad3f5' --preview='head -$LINES {}')







filetype=$(file $selection | awk '{print $2}')


[[ "$filetype" = "directory" ]] && cd $selection
[[ "$filetype" = "PNG" ]] || [[ "$filetype" = "JPEG" ]] && $IMGVIEWER $selection
[[ "$filetype" = "Unicode" ]] || [[ "$filetype" = "Python" ]] || [[ "$filetype" = "ASCII" ]] && $EDITOR $selection




