#!/bin/zsh

chosen=$(nsxiv -ot ~/Pictures/wallpapers/*) 

xwallpaper --zoom $chosen &
betterlockscreen -u $chosen &
echo "xwallpaper --zoom $chosen &\nbetterlockscreen -u $chosen &" > ~/.setwallpaper &
#dunstify "Wallpaper Changed!" ||
#dunstify "Error!"



