#!/bin/sh

selection=$(echo -e "Terminal\nWeb\nCode\nScreenshot\nIncVol\nDecVol\nMuteVol\nSelWall" | rofi -dmenu)

[ "$selection" = "Terminal" ] && kitty
[ "$selection" = "Web" ] && google-chrome-stable
[ "$selection" = "Code" ] && code
[ "$selection" = "Screenshot" ] && flameshot
[ "$selection" = "IncVol" ] && ~/scripts/chvol inc
[ "$selection" = "DecVol" ] && ~/scripts/chvol dec
[ "$selection" = "MuteVol" ] && ~/scripts/chvol mute
[ "$selection" = "SelWall" ] && ~/scripts/selwallpaper
